# Instalación y ejecución de Picrust2

Descripción del capítulo


## Instalación en Mac (procesador intel)

### Instalando conda, nuevo ambiente picrust2, se crean canales, y se instala picrust2

```

curl -L -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh

bash Miniconda3-latest-MacOSX-x86_64.sh

conda --version

conda create -n picrust2 python=3.8 -y

conda activate picrust2

conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge

conda install -c bioconda picrust2 -y

´´´


### Verificando picrust2, 

conda activate picrust2

picrust2_pipeline.py -h


### Corriendo primer ejemplo. Archivos de entrada ASVs_counts.tsv (se agrega "OTU" en primer linea, separado por un tabulador) y archivo ASVs.fa


picrust2_pipeline.py \
  -s ASVs.fa \
  -i ASVs_counts.tsv \
  -o picrust2_results \
  -p 4

#### picrust2_pipeline.py
Es el pipeline principal de PICRUSt2, un flujo completo que:
Coloca las ASVs en un árbol filogenético de referencia.
Predice funciones (KO, EC, MetaCyc pathways).
Calcula el valor NSTI para evaluar la confiabilidad de la predicción.
Genera las tablas funcionales por muestra (estratificadas y no estratificadas).

#### -s asv_seqs.fna
Archivo FASTA con las secuencias ASV.
Contiene las secuencias representativas generadas por DADA2 o QIIME2.
Cada encabezado (>ASV_1, >ASV_2, etc.) debe coincidir exactamente con los IDs en la tabla de conteos.
Deben ser secuencias del gen 16S (PICRUSt2 no funciona con ITS u otros marcadores).
Debe tener formato FASTA estándar.

#### -i asv_table.tsv
Tabla de abundancias (TSV) con los conteos por ASV.
Primera columna: ID del ASV.
Columnas siguientes: cada muestra.
Separación por tabuladores.
Debe coincidir con los IDs de FASTA.

#### -o picrust2_results
Carpeta donde se guardarán todos los resultados.
El pipeline crea automáticamente un directorio con subcarpetas y archivos como:
KO_metagenome_out/ → Predicciones KO (KEGG Orthologs)
EC_metagenome_out/ → Enzyme Commission numbers
pathways_out/ → Predicciones de rutas MetaCyc
marker_predicted_and_nsti.tsv.gz → Valores NSTI por ASV
out.tre → Árbol filogenético con colocación de ASVs
pipeline_log.txt → Registro completo del análisis

#### -p 4
Número de núcleos/threads usados.
Acelera procesos intensivos como HMMER y EPA-NG.
Recomendación general:
Mac Intel 4 núcleos → -p 4
Mac con 8 núcleos → -p 8
Servidores → usar tantos como tengas disponibles


### Subtítulo nivel 2

Contenido
